spring.application.name=Amorix-AI
spring.datasource.url=jdbc:postgresql://localhost:9000/amorixAiDb
spring.datasource.username=admin
spring.datasource.password=ayush@123
spring.datasource.drive.class.name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
wt.secret-key= as9b7aodlbjfkluosfd789ujeklfnlsduf90b8ha908wdvfbgfbfght5yt55y
debug=true